---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: ansible-role-bootstrap

  tasks:
    - name: Test connection
      ping:
      vars:
        ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
