---
- name: Verify
  hosts: all
  gather_facts: no
  become: no

  tasks:
    - name: Test connection
      block:
        - name: Gather facts
          setup:

        - name: Ping
          ping:
      when:
        - bootstrap_ansible_user is undefined

    - name: Test connection (using bootstrap ansible_user)
      block:
        - name: Gather facts
          setup:

        - name: Ping
          ping:
      vars:
        ansible_user: "{{ bootstrap_ansible_user }}"
      when:
        - bootstrap_ansible_user is defined
