---
- name: Verify
  hosts: all
  become: no
  gather_facts: no

  tasks:
    - name: Test connection
      block:
        - setup:
        
        - ping:
      when:
        - bootstrap_ansible_user is undefined

    - name: Test connection (using bootstrap ansible_user)
      block:
        - setup:
        
        - ping:
      vars:
        ansible_user: "{{ bootstrap_ansible_user }}"
      when:
        - bootstrap_ansible_user is defined
