---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://hub.docker.com/search/?type=image
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos_latest}_${TOX_ENVNAME:-docker}"
    image: ${TEST_DOCKER_IMAGE:-centos:latest}
    pre_build_image: yes
    command: ${TEST_DOCKER_COMMAND:-"bash -c 'sleep infinity & wait'"}
    groups:
      - ${TEST_DISTRO:-centos_latest}_docker
provisioner:
  name: ansible
  # ansible_args:
  #   - -vvvv
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
  playbooks:
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
scenario:
  name: default
verifier:
  name: ansible
