---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/finding-an-ami.html
  - name: instance_amazonlinux_latest_ec2
    image: ami-084ab95c0cbe247e5
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    root_device:
      device_name: /dev/xvda
    groups:
      - amazonlinux_latest_ec2
  - name: instance_centos_latest_ec2
    image: ami-dd3c0f36
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - centos_latest_ec2
  - name: instance_redhat_latest_ec2
    image: ami-875042eb
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - redhat_latest_ec2
  - name: instance_debian_latest_ec2
    image: ami-0ca467408e84df23c
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    root_device:
      device_name: xvda
    groups:
      - debian_latest_ec2
  - name: instance_fedora_latest_ec2
    image: ami-0f904cfaa69a1c64c
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - fedora_latest_ec2
  - name: instance_ubuntu_latest_ec2
    image: ami-0cf8fa6a01bb07363
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    groups:
      - ubuntu_latest_ec2
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
  playbooks:
    ec2:
      create: ${TEST_CREATE:-../resources/ec2/create.yml}
      destroy: ${TEST_DESTROY:-../resources/ec2/destroy.yml}
    converge: ${TEST_CONVERGE:-../resources/converge.yml}
    verify: ${TEST_VERIFY:-../resources/verify.yml}
  inventory:
    group_vars:
      amazonlinux_latest_ec2:
        bootstrap_user: ec2-user
      centos_latest_ec2:
        bootstrap_user: centos
      debian_latest_ec2:
        bootstrap_user: admin
      fedora_latest_ec2:
        bootstrap_user: fedora
      redhat_latest_ec2:
        bootstrap_user: ec2-user
      ubuntu_latest_ec2:
        bootstrap_user: ubuntu
scenario:
  name: ec2-all-latest
verifier:
  name: ansible
